
services:
  docker:
    container_name: docker
    image: docker:dind
    privileged: true
    user: root
    restart: unless-stopped
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      - security 

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    depends_on:
      - docker
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - security  
volumes:
  jenkins-docker-certs:

networks:
    security: